name: Selftest

on:
    pull_request

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [macos-13, macos-latest, ubuntu-latest, windows-latest]
                v: [^10, ^11, ^12, ^13, ^14, ""] # Ensure latest version is always tested
                exclude: # Unavailable combos
                    - os: macos-13
                      v: ^10
                    - os: macos-13
                      v: ^11
                    - os: macos-latest
                      v: ^10
                    - os: macos-latest
                      v: ^11
                    - os: macos-latest
                      v: ^12

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Alire
              uses: alire-project/setup-alire@v4
              with:
                  toolchain: gnat_native${{ matrix.v }} gprbuild
                  force: true

            - name: Build and test
              shell: bash
              run: |
                  alr test && cat alire/*.log || { cat alire/*.log; exit 1; }